/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rodiconmc.rodi_forwarder

val hostMap = mutableMapOf<String, String>()

//Example env: RODIFORWARD="alpha.rodiconmc.com;10.0.0.1:25565 beta.rodiconmc.com;10.0.0.2:25565"

fun main() {
    val assignmentString = System.getenv("RODIFORWARD")
    for (pair in assignmentString.split(" ")) {
        val split = pair.split(";")
        hostMap[split[0]] = split[1]
    }

    var port = 25565
    if (System.getenv("LISTENPORT").toInt() > 0) {
        port = System.getenv("LISTENPORT").toInt()
    }
    ForwarderServer(port).run()
}
